/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Craft;
import Model.CraftQueue;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddCraftDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddCraftDetails.class.getName());

    /**
     * Creates new form AddCraftDetails
     */
    public AddCraftDetails() {
        initComponents();
        setSize(1200, 800);
        setLocationRelativeTo(null); // Center on screen
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        Flight_no.setVisible(false);
        flight_no_txt.setVisible(false);
        base.setVisible(false);
        Base_txt.setVisible(false);
        Tail_number.setVisible(false);
        tail_no_txt.setVisible(false);
        Serial_no.setVisible(false);
        serialno_txt.setVisible(false);
        
        String depart_time = departure_time_txt.getText().trim();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        craftTypeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Craft_Type = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Model_No = new javax.swing.JLabel();
        Flight_no = new javax.swing.JLabel();
        Purpose = new javax.swing.JLabel();
        Destination = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        Departure_time = new javax.swing.JLabel();
        Tail_number = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        engine_Type = new javax.swing.JLabel();
        Serial_no = new javax.swing.JLabel();
        engine_type_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        model_number_txt = new javax.swing.JTextField();
        Destination_txt = new javax.swing.JTextField();
        departure_time_txt = new javax.swing.JTextField();
        flight_no_txt = new javax.swing.JTextField();
        Base_txt = new javax.swing.JTextField();
        serialno_txt = new javax.swing.JTextField();
        tail_no_txt = new javax.swing.JTextField();
        type_combo = new javax.swing.JComboBox<>();
        Purpose_combo = new javax.swing.JComboBox<>();
        status_combo = new javax.swing.JComboBox<>();
        Spacecraft_button = new javax.swing.JRadioButton();
        Aircraft_button = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name : ");
        jLabel8.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Craft Details");

        jPanel1.setBackground(new java.awt.Color(47, 59, 105));

        Craft_Type.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Craft_Type.setForeground(new java.awt.Color(255, 255, 255));
        Craft_Type.setText("Craft Type:");
        Craft_Type.setToolTipText("");

        Name.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name : ");
        Name.setToolTipText("");

        Model_No.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Model_No.setForeground(new java.awt.Color(255, 255, 255));
        Model_No.setText("Model no :");
        Model_No.setToolTipText("");

        Flight_no.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Flight_no.setForeground(new java.awt.Color(255, 255, 255));
        Flight_no.setText("Flight no :");
        Flight_no.setToolTipText("");

        Purpose.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Purpose.setForeground(new java.awt.Color(255, 255, 255));
        Purpose.setText("Purpose :");
        Purpose.setToolTipText("");

        Destination.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Destination.setForeground(new java.awt.Color(255, 255, 255));
        Destination.setText("Destination :");
        Destination.setToolTipText("");

        Status.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Status.setForeground(new java.awt.Color(255, 255, 255));
        Status.setText("Status :");
        Status.setToolTipText("");

        Type.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setText("Type :");
        Type.setToolTipText("");

        Departure_time.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Departure_time.setForeground(new java.awt.Color(255, 255, 255));
        Departure_time.setText("Departure Time :");
        Departure_time.setToolTipText("");

        Tail_number.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Tail_number.setForeground(new java.awt.Color(255, 255, 255));
        Tail_number.setText("Tail Number :");
        Tail_number.setToolTipText("");

        base.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        base.setForeground(new java.awt.Color(255, 255, 255));
        base.setText("Base :");
        base.setToolTipText("");

        engine_Type.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        engine_Type.setForeground(new java.awt.Color(255, 255, 255));
        engine_Type.setText("Engine Type :");
        engine_Type.setToolTipText("");

        Serial_no.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Serial_no.setForeground(new java.awt.Color(255, 255, 255));
        Serial_no.setText("Serial no :");
        Serial_no.setToolTipText("");

        engine_type_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        name_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        model_number_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        Destination_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Destination_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destination_txtActionPerformed(evt);
            }
        });

        departure_time_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        departure_time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departure_time_txtActionPerformed(evt);
            }
        });

        flight_no_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        Base_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        serialno_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        tail_no_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tail_no_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tail_no_txtActionPerformed(evt);
            }
        });

        type_combo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tropospheric", "Stratospheric", "LEO", "Interstellar" }));
        type_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_comboActionPerformed(evt);
            }
        });

        Purpose_combo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Purpose_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Commerical", "Private", "Research", "Millitary" }));

        status_combo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        status_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On-Board", "Yet to Board", "Delayed", "Boarded" }));
        status_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_comboActionPerformed(evt);
            }
        });

        craftTypeGroup.add(Spacecraft_button);
        Spacecraft_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Spacecraft_button.setText("Space Craft");
        Spacecraft_button.setOpaque(true);
        Spacecraft_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spacecraft_buttonActionPerformed(evt);
            }
        });

        craftTypeGroup.add(Aircraft_button);
        Aircraft_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Aircraft_button.setText("Aircraft");
        Aircraft_button.setOpaque(true);
        Aircraft_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aircraft_buttonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Model_No, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Craft_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Aircraft_button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Spacecraft_button, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(engine_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(engine_type_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Serial_no, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serialno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Flight_no, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(309, 309, 309)
                                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(flight_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(Destination_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Purpose_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(226, 226, 226)
                                .addComponent(Tail_number, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tail_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Departure_time, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(departure_time_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192)
                                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Base_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(159, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Model_No, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Craft_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Aircraft_button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spacecraft_button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Flight_no, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flight_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Destination_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tail_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tail_number, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departure_time_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departure_time, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Base_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engine_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engine_type_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Serial_no, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Purpose_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Destination_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destination_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Destination_txtActionPerformed

    private void departure_time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departure_time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departure_time_txtActionPerformed

    private void tail_no_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tail_no_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tail_no_txtActionPerformed

    private void status_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_comboActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    String depart_time = departure_time_txt.getText().trim();
    if (name_txt.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter craft name");
    return;                
    }
    if (!Aircraft_button.isSelected() && !Spacecraft_button.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select craft type (Aircraft or Spacecraft)");
        return;
    }
    if (type_combo.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this, "Please select type of the craft.");
        return;
    }
    if (Destination_txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the destination");
        return;
    }
    if (departure_time_txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter departure time");
        return;
    }
    if (!depart_time.matches("([01]?\\d|2[0-3]):[0-5]\\d")) {
        JOptionPane.showMessageDialog(this, "Enter time in HH:mm format! Example: 09:30 or 23:15");
        return;
        
    }if (engine_type_txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter engine type");
        return;
    }
    if (Purpose_combo.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this, "Please select purpose of the craft");
        return;
    }
    if (model_number_txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter model number");
        return;
    } 
        if (status_combo.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this, "Please select status of the craft");
        return;
    }
    String selectedType = type_combo.getSelectedItem().toString();

// AIRCRAFT LOGIC
if (Aircraft_button.isSelected()) {
    
    if (model_number_txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter model number");
        return;
    }

    if (selectedType.equals("Tropospheric")) {
        Flight_no.setVisible(true);
        flight_no_txt.setVisible(true);

        if (flight_no_txt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter flight number");
            return;
        }

    } else if (selectedType.equals("Stratospheric")) {
        base.setVisible(true);
        Base_txt.setVisible(true);
        Tail_number.setVisible(true);
        tail_no_txt.setVisible(true);

        if (Base_txt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter base");
            return;
        }

        if (tail_no_txt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter tail number");
            return;
        }
    }
}

// SPACECRAFT LOGIC
else if (Spacecraft_button.isSelected()) {
    Serial_no.setVisible(true);
    serialno_txt.setVisible(true);
    if (serialno_txt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter spacecraft serial number");
        return;
    }
}

    
    // Create the craft object
    Craft craft = new Craft(
        name_txt.getText().trim(),                              
        model_number_txt.getText().trim(),                      // 2. modelNo
        flight_no_txt.getText().trim(),                         // 3. flightNo
        engine_type_txt.getText().trim(),                       // 4. engineType
        Destination_txt.getText().trim(),                       // 5. destination
        departure_time_txt.getText().trim(),                    // 6. departureTime
        tail_no_txt.getText().trim(),                          // 7. tailNumber
        Base_txt.getText().trim(),                             // 8. base
        type_combo.getSelectedItem().toString(),               // 9. type (Troposheric, etc.)
        Purpose_combo.getSelectedItem().toString(),            // 10. purpose (Commercial, etc.) - FIXED!
        status_combo.getSelectedItem().toString(),             // 11. status (On-Board, etc.)
        Aircraft_button.isSelected() ? "Aircraft" : "Spacecraft", // 12. craftType
        serialno_txt.getText().trim()
    );
    
    CraftQueue.addCraft(craft); // Add to queue
    
    JOptionPane.showMessageDialog(this, "Craft added successfully!");
    
    dispose(); // Close the dialog
    }//GEN-LAST:event_saveButtonActionPerformed

    private void Aircraft_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aircraft_buttonActionPerformed
        // TODO add your handling code here:
    Serial_no.setVisible(false);
    serialno_txt.setVisible(false);
    base.setVisible(false);
    Base_txt.setVisible(false);
    Tail_number.setVisible(false);
    tail_no_txt.setVisible(false);
    Flight_no.setVisible(false);
    flight_no_txt.setVisible(false);
    type_combo.removeActionListener(type_combo.getActionListeners()[0]);

    type_combo.removeAllItems();
    type_combo.addItem("Tropospheric");
    type_combo.addItem("Stratospheric");

    // Re-add listener
    type_combo.addActionListener(this::type_comboActionPerformed);
    

    }//GEN-LAST:event_Aircraft_buttonActionPerformed

    private void Spacecraft_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spacecraft_buttonActionPerformed
        // TODO add your handling code here:
    base.setVisible(false);
    Base_txt.setVisible(false);
    Tail_number.setVisible(false);
    tail_no_txt.setVisible(false);
    Flight_no.setVisible(false);
    flight_no_txt.setVisible(false);
    Serial_no.setVisible(true);
    serialno_txt.setVisible(true);
    
    type_combo.removeActionListener(type_combo.getActionListeners()[0]);
    type_combo.removeAllItems();
    type_combo.addItem("LEO");
    type_combo.addItem("Interstellar");
    type_combo.addActionListener(this::type_comboActionPerformed);

    }//GEN-LAST:event_Spacecraft_buttonActionPerformed

    private void type_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_comboActionPerformed
        // TODO add your handling code here:
        if(type_combo.getSelectedItem().toString().equals("Tropospheric")){
        Flight_no.setVisible(true);
        flight_no_txt.setVisible(true);

        base.setVisible(false);
        Base_txt.setVisible(false);
        Tail_number.setVisible(false);
        tail_no_txt.setVisible(false);  
        }else if(type_combo.getSelectedItem().toString().equals("Stratospheric")){
        base.setVisible(true);
        Base_txt.setVisible(true);
        Tail_number.setVisible(true);
        tail_no_txt.setVisible(true);

        Flight_no.setVisible(false);
        flight_no_txt.setVisible(false);
    }
    }//GEN-LAST:event_type_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddCraftDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aircraft_button;
    private javax.swing.JTextField Base_txt;
    private javax.swing.JLabel Craft_Type;
    private javax.swing.JLabel Departure_time;
    private javax.swing.JLabel Destination;
    private javax.swing.JTextField Destination_txt;
    private javax.swing.JLabel Flight_no;
    private javax.swing.JLabel Model_No;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Purpose;
    private javax.swing.JComboBox<String> Purpose_combo;
    private javax.swing.JLabel Serial_no;
    private javax.swing.JRadioButton Spacecraft_button;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Tail_number;
    private javax.swing.JLabel Type;
    private javax.swing.JLabel base;
    private javax.swing.ButtonGroup craftTypeGroup;
    private javax.swing.JTextField departure_time_txt;
    private javax.swing.JLabel engine_Type;
    private javax.swing.JTextField engine_type_txt;
    private javax.swing.JTextField flight_no_txt;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField model_number_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField serialno_txt;
    private javax.swing.JComboBox<String> status_combo;
    private javax.swing.JTextField tail_no_txt;
    private javax.swing.JComboBox<String> type_combo;
    // End of variables declaration//GEN-END:variables
}
