/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Model.Craft;

/**
 *
 * @author ASUS
 */
public class CraftPanel extends javax.swing.JPanel {

    /**
     * Creates new form CraftPanel
     */
    private Craft craft; 
    
    public CraftPanel() {
        initComponents();
        save_btn.setVisible(false);
        
        
    }
    public CraftPanel(Craft craft) {
        this(); // Calls the no-arg constructor first
        this.craft = craft;
        populatePanel(); // Custom method to set data on the panel
        
        
    }
    private void populatePanel() {

    // Hide everything first (reset state)
    jLabel1.setVisible(false);       // Flight No
    jTextField8.setVisible(false);

    jLabel9.setVisible(false);       // Base
    jTextField10.setVisible(false);

    Serialnum.setVisible(false);     // Serial / Tail
    Serialno.setVisible(false);

    jLabel7.setVisible(true);        // Model No
    jTextField11.setVisible(true);

    if (craft == null) return;

    // Common fields
    jTextField7.setText(craft.getName());
    jTextField1.setText(craft.getCraftType());
    jTextField2.setText(craft.getEngineType());
    jTextField3.setText(craft.getDepartureTime());
    jTextField4.setText(craft.getDestination());
    jTextField5.setText(craft.getType());
    jTextField6.setText(craft.getPurpose());
    jTextField11.setText(craft.getModelNo());

    // ================= AIRCRAFT =================
    if (craft.getCraftType().equals("Aircraft")) {

        if (craft.getType().equals("Tropospheric")) {
            // Flight No + Model No
            jLabel1.setVisible(true);
            jTextField8.setVisible(true);
            jTextField8.setText(craft.getFlightNo());
        }

        else if (craft.getType().equals("Stratospheric")) {
            // Base + Tail No + Model No
            jLabel9.setVisible(true);
            jTextField10.setVisible(true);
            jTextField10.setText(craft.getBase());

            Serialnum.setText("Tail No :");
            Serialnum.setVisible(true);
            Serialno.setVisible(true);
            Serialno.setText(craft.getTailNumber());
        }
    }

    // ================= SPACECRAFT =================
    else if (craft.getCraftType().equals("Spacecraft")) {

        Serialnum.setText("Serial No :");
        Serialnum.setVisible(true);
        Serialno.setVisible(true);
        Serialno.setText(craft.getSerialNo());

        // Ensure Aircraft-only fields stay hidden
        jLabel1.setVisible(false);
        jTextField8.setVisible(false);
        jLabel9.setVisible(false);
        jTextField10.setVisible(false);
    }

    // Make all fields read-only
    jTextField1.setEditable(false);
    jTextField2.setEditable(false);
    jTextField3.setEditable(false);
    jTextField4.setEditable(false);
    jTextField5.setEditable(false);
    jTextField6.setEditable(false);
    jTextField7.setEditable(false);
    jTextField8.setEditable(false);
    Serialno.setEditable(false);
    jTextField10.setEditable(false);
    jTextField11.setEditable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Serialnum = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        Serialno = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        del_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        spacepng = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 120));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight No :");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 120, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Engine Type:");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 130, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Destination :");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 140, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Departure Time :");
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type :");
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 90, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Purpose :");
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 110, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Model no :");
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 120, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Name :");
        jLabel8.setOpaque(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Base :");
        jLabel9.setOpaque(true);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 120, 40));

        Serialnum.setBackground(new java.awt.Color(255, 255, 255));
        Serialnum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Serialnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Serialnum.setText("Serial no :");
        Serialnum.setOpaque(true);
        add(Serialnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 120, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Craft Type :");
        jLabel12.setOpaque(true);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 120, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tail no :");
        jLabel13.setOpaque(true);
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 120, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 210, 40));

        jTextField2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 310, 40));

        jTextField3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 170, 40));

        jTextField4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 280, 40));

        jTextField5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 220, 40));

        jTextField6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 190, 40));

        jTextField7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, 40));

        jTextField8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 170, 40));

        Serialno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(Serialno, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 170, 40));

        jTextField10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 210, 40));

        jTextField11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 170, 40));

        del_btn.setBackground(new java.awt.Color(0, 0, 90));
        del_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        del_btn.setForeground(new java.awt.Color(255, 255, 255));
        del_btn.setText("Delete");
        add(del_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 110, -1));

        edit_btn.setBackground(new java.awt.Color(0, 0, 90));
        edit_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 110, -1));

        jTextField12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 170, 40));

        save_btn.setBackground(new java.awt.Color(0, 0, 90));
        save_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 110, -1));

        spacepng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/space.png"))); // NOI18N
        spacepng.setMaximumSize(new java.awt.Dimension(1000, 700));
        spacepng.setMinimumSize(new java.awt.Dimension(1000, 700));
        spacepng.setPreferredSize(new java.awt.Dimension(1000, 700));
        add(spacepng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
    jTextField1.setEditable(true);
    jTextField2.setEditable(true);
    jTextField3.setEditable(true);
    jTextField4.setEditable(true);
    jTextField5.setEditable(true);
    jTextField6.setEditable(true);
    jTextField7.setEditable(true);
    jTextField8.setEditable(true);
    Serialno.setEditable(true);
    jTextField10.setEditable(true);
    jTextField11.setEditable(true);
    

    // Hide Edit button, show Save button
    edit_btn.setVisible(false);
    del_btn.setVisible(false);
    save_btn.setVisible(true);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        if(craft != null){
        craft.setName(jTextField7.getText());
        craft.setCraftType(jTextField1.getText());
        craft.setEngineType(jTextField2.getText());
        craft.setDepartureTime(jTextField3.getText());
        craft.setDestination(jTextField4.getText());
        craft.setType(jTextField5.getText());
        craft.setPurpose(jTextField6.getText());
        craft.setModelNo(jTextField11.getText());

        if(craft.getCraftType().equals("Aircraft")){
            craft.setFlightNo(jTextField8.getText());
        } else if(craft.getCraftType().equals("Spacecraft")){
            craft.setBase(jTextField10.getText());
            craft.setTailNumber(Serialno.getText());
        }

        // Make fields read-only again
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        Serialno.setEditable(false);
        jTextField10.setEditable(false);
        jTextField11.setEditable(false);

        // Hide Save button, show Edit button
        save_btn.setVisible(false);
        edit_btn.setVisible(true);
        del_btn.setVisible(true);
        
        this.revalidate();
        this.repaint();

        // Optional: Show confirmation
        javax.swing.JOptionPane.showMessageDialog(this, "Craft updated successfully!");
        }
    }//GEN-LAST:event_save_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Serialno;
    private javax.swing.JLabel Serialnum;
    private javax.swing.JButton del_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel spacepng;
    // End of variables declaration//GEN-END:variables
}
