/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.User;
import Controller.CraftController;
import Controller.LoginController;
import java.awt.CardLayout;
import java.io.IOException;
import java.net.URISyntaxException;
import Model.Craft;
//import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */


public class loginPage extends javax.swing.JFrame {
    private boolean isAdmin = false;
    private boolean nameSortAsc = true;
    private final CraftController craftController = new CraftController();
    private final LoginController loginController = new LoginController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(loginPage.class.getName());

    /**
     * Creates new form loginPage
     */
    public loginPage() {
        initComponents();
        savebtn1.setVisible(false);
        search.setText("Search by name");
        search.setForeground(java.awt.Color.GRAY);
        
         Main_Content.setVisible(false);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(false);

        CardLayout card = new CardLayout();
        getContentPane().setLayout(card);

        getContentPane().add(login_panel, "login");
        getContentPane().add(Dashboard_Panel, "dashboard");
        getContentPane().add(signUp_Panel, "signup");
        // show login first
        card.show(getContentPane(), "login");
    }

    private void applyDashboardPrivileges() {
        // Only admin can add crafts
        Add.setVisible(isAdmin);
        Add.setEnabled(isAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        Sign_up = new javax.swing.JLabel();
        new_user = new javax.swing.JLabel();
        Usernamefield_login = new javax.swing.JTextField();
        PsField_login = new javax.swing.JPasswordField();
        login_button = new javax.swing.JLabel();
        Password_login = new javax.swing.JLabel();
        Username_login = new javax.swing.JLabel();
        login_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dashboard_Panel = new javax.swing.JPanel();
        Nav_Panel = new javax.swing.JPanel();
        motto = new javax.swing.JLabel();
        Aeromaze = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        spacecraft_icon = new javax.swing.JLabel();
        home_icon = new javax.swing.JLabel();
        aircraft_icon = new javax.swing.JLabel();
        profile_icon = new javax.swing.JLabel();
        news_icon = new javax.swing.JLabel();
        Main_Content = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        main_motto1 = new javax.swing.JLabel();
        main_motto2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        Sortbyname = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        earth = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        undo = new javax.swing.JButton();
        recentlyadded = new javax.swing.JTextField();
        DELETED = new javax.swing.JTextField();
        recentlydeletedfield = new javax.swing.JLabel();
        recentlyaddedtext = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dashboard_table = new javax.swing.JTable();
        aircraft_Panel = new javax.swing.JPanel();
        top_Panel = new javax.swing.JPanel();
        reload = new javax.swing.JButton();
        searcher = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 32767));
        Spacecraft_Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Reoad_space = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 32767));
        Profile_Panel = new javax.swing.JPanel();
        savebtn1 = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        contact_txtfield = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        Designation = new javax.swing.JLabel();
        psfield_profile = new javax.swing.JTextField();
        designation = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        name_txtfield = new javax.swing.JTextField();
        Profile_name = new javax.swing.JLabel();
        Profile_Panel_Photo = new javax.swing.JLabel();
        psfield_profile1 = new javax.swing.JTextField();
        News_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        news_photo = new javax.swing.JLabel();
        signUp_Panel = new javax.swing.JPanel();
        Signup_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        signup_panel_photo = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1536, 960));
        getContentPane().setLayout(new java.awt.CardLayout());

        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sign_up.setFont(new java.awt.Font("STXihei", 3, 20)); // NOI18N
        Sign_up.setForeground(new java.awt.Color(255, 255, 255));
        Sign_up.setText("Sign Up");
        Sign_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_upMouseClicked(evt);
            }
        });
        login_panel.add(Sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 770, 80, -1));

        new_user.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        new_user.setForeground(new java.awt.Color(255, 255, 255));
        new_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        new_user.setText("New User ? ");
        login_panel.add(new_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 770, -1, -1));

        Usernamefield_login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Usernamefield_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usernamefield_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usernamefield_loginActionPerformed(evt);
            }
        });
        login_panel.add(Usernamefield_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 270, 50));

        PsField_login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        PsField_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PsField_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsField_loginActionPerformed(evt);
            }
        });
        login_panel.add(PsField_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 260, 50));

        login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/login_button 89.png"))); // NOI18N
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
        });
        login_panel.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 250, 110));

        Password_login.setFont(new java.awt.Font("Times New Roman", 0, 34)); // NOI18N
        Password_login.setForeground(new java.awt.Color(255, 255, 255));
        Password_login.setText("PASSWORD");
        login_panel.add(Password_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        Username_login.setFont(new java.awt.Font("Times New Roman", 0, 34)); // NOI18N
        Username_login.setForeground(new java.awt.Color(255, 255, 255));
        Username_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username_login.setText("USERNAME");
        login_panel.add(Username_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 210, 50));

        login_icon.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        login_icon.setForeground(new java.awt.Color(255, 255, 255));
        login_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_icon.setText("LOG IN");
        login_panel.add(login_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 160, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/login page (1).png"))); // NOI18N
        login_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(login_panel, "card3");

        Dashboard_Panel.setMinimumSize(new java.awt.Dimension(1536, 960));
        Dashboard_Panel.setPreferredSize(new java.awt.Dimension(1536, 960));
        Dashboard_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nav_Panel.setBackground(new java.awt.Color(15, 25, 62));
        Nav_Panel.setMinimumSize(new java.awt.Dimension(400, 960));
        Nav_Panel.setPreferredSize(new java.awt.Dimension(400, 960));
        Nav_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        motto.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        motto.setForeground(new java.awt.Color(187, 191, 240));
        motto.setText("PIONEERING THE SKIES");
        Nav_Panel.add(motto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, -1));

        Aeromaze.setBackground(new java.awt.Color(255, 255, 255));
        Aeromaze.setFont(new java.awt.Font("Times New Roman", 1, 43)); // NOI18N
        Aeromaze.setForeground(new java.awt.Color(255, 255, 255));
        Aeromaze.setText("AEROMAZE");
        Nav_Panel.add(Aeromaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 50));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo.png"))); // NOI18N
        Nav_Panel.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, 130, 150));

        spacecraft_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spacecraft_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/spaceicon3.png"))); // NOI18N
        spacecraft_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spacecraft_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spacecraft_iconMouseClicked(evt);
            }
        });
        Nav_Panel.add(spacecraft_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 130, 130));

        home_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/home incon.png"))); // NOI18N
        home_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_iconMouseClicked(evt);
            }
        });
        Nav_Panel.add(home_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        aircraft_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aircraft_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/aeri.png"))); // NOI18N
        aircraft_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aircraft_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aircraft_iconMouseClicked(evt);
            }
        });
        Nav_Panel.add(aircraft_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        profile_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/profile.png"))); // NOI18N
        profile_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_iconMouseClicked(evt);
            }
        });
        Nav_Panel.add(profile_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, -1));

        news_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        news_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/news.png"))); // NOI18N
        news_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        news_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                news_iconMouseClicked(evt);
            }
        });
        Nav_Panel.add(news_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 800, 90, 90));

        Dashboard_Panel.add(Nav_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        Main_Content.setBackground(new java.awt.Color(220, 227, 255));
        Main_Content.setMinimumSize(new java.awt.Dimension(1136, 960));
        Main_Content.setPreferredSize(new java.awt.Dimension(1136, 960));
        Main_Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Add.setText("Add");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        Main_Content.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 90, -1));

        Refresh.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        Main_Content.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 140, -1));

        main_motto1.setFont(new java.awt.Font("Bodoni MT", 0, 40)); // NOI18N
        main_motto1.setForeground(new java.awt.Color(255, 255, 255));
        main_motto1.setText("NAVIGATION YOU CAN TRUST");
        Main_Content.add(main_motto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        main_motto2.setFont(new java.awt.Font("STXihei", 0, 24)); // NOI18N
        main_motto2.setForeground(new java.awt.Color(117, 185, 255));
        main_motto2.setText("Soaring skies, Mastering space");
        Main_Content.add(main_motto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        search.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        Main_Content.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 262, 210, 50));

        Sortbyname.setBackground(new java.awt.Color(0, 6, 121));
        Sortbyname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Sortbyname.setForeground(new java.awt.Color(255, 255, 255));
        Sortbyname.setText("Sort by Name");
        Sortbyname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SortbynameMouseClicked(evt);
            }
        });
        Sortbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortbynameActionPerformed(evt);
            }
        });
        Main_Content.add(Sortbyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 40));

        searchbtn.setBackground(new java.awt.Color(0, 0, 140));
        searchbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        Main_Content.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, 40));

        earth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/EARTH.png"))); // NOI18N
        Main_Content.add(earth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(153, 255, 153));
        jPanel5.setMinimumSize(new java.awt.Dimension(45, 160));
        jPanel5.setPreferredSize(new java.awt.Dimension(45, 160));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        undo.setBackground(new java.awt.Color(0, 0, 121));
        undo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        undo.setForeground(new java.awt.Color(255, 255, 255));
        undo.setText("Undo ");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        jPanel5.add(undo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 80, 40));

        recentlyadded.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        recentlyadded.setText("RECENTLY ADDED");
        recentlyadded.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        recentlyadded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recentlyaddedActionPerformed(evt);
            }
        });
        jPanel5.add(recentlyadded, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 40));

        DELETED.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        DELETED.setText("RECENTLY DELETED");
        DELETED.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DELETED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEDActionPerformed(evt);
            }
        });
        jPanel5.add(DELETED, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 30));

        recentlydeletedfield.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        recentlydeletedfield.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recentlydeletedfield.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(recentlydeletedfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 520, 240));

        recentlyaddedtext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        recentlyaddedtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recentlyaddedtext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(recentlyaddedtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 520, 240));

        Main_Content.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 570, 610));

        Dashboard_table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Name", "Craft Type", "Purpose"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        Dashboard_table.setRowHeight(40);
        jScrollPane2.setViewportView(Dashboard_table);

        Main_Content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 610, 610));

        Dashboard_Panel.add(Main_Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 0, 1240, -1));

        aircraft_Panel.setBackground(new java.awt.Color(255, 255, 255));
        aircraft_Panel.setMinimumSize(new java.awt.Dimension(1236, 960));
        aircraft_Panel.setPreferredSize(new java.awt.Dimension(1236, 960));
        aircraft_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_Panel.setBackground(new java.awt.Color(102, 102, 255));
        top_Panel.setMinimumSize(new java.awt.Dimension(1136, 200));
        top_Panel.setName(""); // NOI18N
        top_Panel.setPreferredSize(new java.awt.Dimension(1136, 200));
        top_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reload.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        reload.setText("Re-Load");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        top_Panel.add(reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 130, 40));

        searcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/EARTH.png"))); // NOI18N
        searcher.setMaximumSize(new java.awt.Dimension(1136, 200));
        searcher.setMinimumSize(new java.awt.Dimension(1136, 200));
        searcher.setRequestFocusEnabled(false);
        top_Panel.add(searcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 200));

        aircraft_Panel.add(top_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jScrollPane1.setViewportView(jPanel2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(filler1);

        jScrollPane1.setViewportView(jPanel2);

        aircraft_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Dashboard_Panel.add(aircraft_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        Spacecraft_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Spacecraft_Panel.setMinimumSize(new java.awt.Dimension(1236, 960));
        Spacecraft_Panel.setPreferredSize(new java.awt.Dimension(1236, 960));
        Spacecraft_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1136, 240));
        jPanel1.setMinimumSize(new java.awt.Dimension(1136, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(1136, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reoad_space.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Reoad_space.setLabel("Re-Load");
        Reoad_space.setMaximumSize(new java.awt.Dimension(99, 32));
        Reoad_space.setMinimumSize(new java.awt.Dimension(99, 32));
        Reoad_space.setPreferredSize(new java.awt.Dimension(99, 32));
        Reoad_space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reoad_spaceActionPerformed(evt);
            }
        });
        jPanel1.add(Reoad_space, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 120, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/EARTH.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 200));

        Spacecraft_Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(1000, 700));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1000, 700));
        jScrollPane3.setVerifyInputWhenFocusTarget(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler2);

        jScrollPane3.setViewportView(jPanel4);

        Spacecraft_Panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Dashboard_Panel.add(Spacecraft_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        Profile_Panel.setBackground(new java.awt.Color(153, 255, 153));
        Profile_Panel.setMaximumSize(new java.awt.Dimension(1236, 960));
        Profile_Panel.setMinimumSize(new java.awt.Dimension(1236, 960));
        Profile_Panel.setPreferredSize(new java.awt.Dimension(1236, 960));
        Profile_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        savebtn1.setBackground(new java.awt.Color(1, 11, 97));
        savebtn1.setFont(new java.awt.Font("Noto Serif HK", 1, 20)); // NOI18N
        savebtn1.setForeground(new java.awt.Color(255, 255, 255));
        savebtn1.setText("Save");
        savebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn1ActionPerformed(evt);
            }
        });
        Profile_Panel.add(savebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 850, 130, 50));

        edit_btn.setBackground(new java.awt.Color(1, 11, 97));
        edit_btn.setFont(new java.awt.Font("Noto Serif HK", 1, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("EDIT");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        Profile_Panel.add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 850, 130, 50));

        logout_button.setBackground(new java.awt.Color(1, 11, 97));
        logout_button.setFont(new java.awt.Font("Noto Serif HK", 1, 18)); // NOI18N
        logout_button.setForeground(new java.awt.Color(255, 255, 255));
        logout_button.setText("LOG OUT");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        Profile_Panel.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 850, 130, 50));

        contact_txtfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contact_txtfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Profile_Panel.add(contact_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 720, 220, -1));

        Contact.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        Contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contact.setText("CONTACT :");
        Profile_Panel.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 720, -1, -1));

        Designation.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        Designation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Designation.setText("DESIGNATION :");
        Designation.setToolTipText("");
        Profile_Panel.add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, -1));

        psfield_profile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        psfield_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psfield_profileActionPerformed(evt);
            }
        });
        Profile_Panel.add(psfield_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 220, 40));

        designation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationActionPerformed(evt);
            }
        });
        Profile_Panel.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 190, 40));

        Password.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setText("PASSWORD :");
        Profile_Panel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        name_txtfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        name_txtfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Profile_Panel.add(name_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 260, -1));

        Profile_name.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        Profile_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile_name.setText("NAME :");
        Profile_Panel.add(Profile_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        Profile_Panel_Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/moon.png"))); // NOI18N
        Profile_Panel.add(Profile_Panel_Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1240, 1020));

        psfield_profile1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Profile_Panel.add(psfield_profile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 210, 40));

        Dashboard_Panel.add(Profile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        News_Panel.setBackground(new java.awt.Color(0, 153, 153));
        News_Panel.setMinimumSize(new java.awt.Dimension(1236, 960));
        News_Panel.setPreferredSize(new java.awt.Dimension(1236, 960));
        News_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(30, 30, 114));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Big Flips: How cosmic rays grounded a fleet of aircraft");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        News_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 810, 70));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flares.png"))); // NOI18N
        jLabel5.setOpaque(true);
        News_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 360, 200));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/voyager1.png"))); // NOI18N
        jLabel6.setOpaque(true);
        News_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 360, 270));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Untitled design.png"))); // NOI18N
        jLabel7.setOpaque(true);
        News_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, 220));

        jLabel8.setBackground(new java.awt.Color(2, 8, 86));
        jLabel8.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(
                "<html>\nRadiation from space that led to more than 6,000 Airbus aircraft<br>\nneeding emergency computer updates could become a growing<br>\nproblem as ever more microchips run our lives.\nSubatomic particles that may trigger bit flips can originate in huge solar flares ejected by our Sun but they also arrive continually from sources outside our Solar System many light years away, <br>and even from beyond our home galaxy, the Milky Way.\n</html>\n");
        jLabel8.setOpaque(true);
        News_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 700, 140));

        jLabel9.setBackground(new java.awt.Color(2, 8, 86));
        jLabel9.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(
                "<html>\nVoyager 1, NASA’s deep-space probe, could soon become the first spacecraft<br>\nto reach a historic milestone. In November 2026, the probe will be one light-day from Earth.<br>\nbut scientists have to prove it actually exists first.<br>\nLaunched in 1977, Voyager 1 is the farthest spacecraft from our planet, currently exploring<br>\ninterstellar space 15.8 billion miles away.<br>\nOne light-day is equivalent to 16 billion miles.\nSo if Voyager’s team is asking the spacecraft to do something once it reaches that point, <br>\nit will take another day for Voyager to respond.\n\n</html>\n");
        jLabel9.setOpaque(true);
        News_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, 710, 220));

        jLabel10.setBackground(new java.awt.Color(2, 8, 86));
        jLabel10.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(
                "<html>\nThe Hubble Tension is one of the great mysteries of cosmology.<br>\nSolving it might require a fundamental change in how we understand the universe,<br>\nbut scientists have to prove it actually exists first.<br>\nA new paper from the TDCOSMO Collaboration presents updated measurements of the<br>\nHubble Constant using gravitational lenses of quasars, suggesting the tension exists.\n</html>\n");
        jLabel10.setOpaque(true);
        News_Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 700, 140));

        jLabel11.setBackground(new java.awt.Color(30, 30, 114));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(
                "<html>\nVoyager 1 will reach one light-day from Earth in 2026. <br>Here’s what that means </html> ");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        News_Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 810, 70));

        jLabel12.setBackground(new java.awt.Color(30, 30, 114));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("<html> Gravitational Lenses Deliver a Verdict on the Hubble <br> Telescope </html> ");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        News_Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 810, 70));

        news_photo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        news_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/neslett.jpg"))); // NOI18N
        news_photo.setText("jLabel1");
        news_photo.setMaximumSize(new java.awt.Dimension(1136, 960));
        news_photo.setMinimumSize(new java.awt.Dimension(1136, 960));
        news_photo.setPreferredSize(new java.awt.Dimension(1136, 960));
        News_Panel.add(news_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        Dashboard_Panel.add(News_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        getContentPane().add(Dashboard_Panel, "card3");

        signUp_Panel.setMinimumSize(new java.awt.Dimension(1536, 960));
        signUp_Panel.setName(""); // NOI18N
        signUp_Panel.setPreferredSize(new java.awt.Dimension(1536, 960));
        signUp_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Signup_label.setFont(new java.awt.Font("Noto Serif HK", 1, 45)); // NOI18N
        Signup_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Signup_label.setText("SIGN UP");
        signUp_Panel.add(Signup_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 210, 60));

        jLabel3.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password :");
        signUp_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 190, 60));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signUp_Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 370, 310, 60));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signUp_Panel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, 280, 60));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signUp_Panel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 310, 60));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signUp_Panel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 650, 310, 60));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        signUp_Panel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, 310, 60));

        jLabel4.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirm Password :");
        signUp_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 310, 60));

        jLabel13.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Contact :");
        signUp_Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 160, 60));

        jLabel14.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Address :");
        signUp_Panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 160, 60));

        jLabel15.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Username :");
        signUp_Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 190, 60));

        jButton1.setBackground(new java.awt.Color(9, 0, 97));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        signUp_Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 810, 180, 60));

        signup_panel_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/signup page.png"))); // NOI18N
        signUp_Panel.add(signup_panel_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(signUp_Panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_login_buttonMouseClicked

        String username = Usernamefield_login.getText();
        String password = String.valueOf(PsField_login.getPassword());

        LoginController.LoginResult result =
                loginController.login(username, password);

        if (!result.success) {
            JOptionPane.showMessageDialog(this, result.error, "Login Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (result.admin) {
            isAdmin = true;
            applyDashboardPrivileges();

            name_txtfield.setText("admin");
            psfield_profile.setText(result.adminPassword);
            designation.setText("Admin");
            contact_txtfield.setText("9840262982");
        } else {
            isAdmin = false;
            applyDashboardPrivileges();

            User u = result.user;
            name_txtfield.setText(u.getUsername());
            psfield_profile.setText(u.getPassword());
            designation.setText(u.getDesignation());
            contact_txtfield.setText(u.getContact());
        }

        name_txtfield.setEditable(false);
        psfield_profile.setEditable(false);
        designation.setEditable(false);

        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "dashboard");
        Main_Content.setVisible(true);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(false);
    }
    private void home_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_home_iconMouseClicked
        // TODO add your handling code here:public void
        // mouseClicked(java.awt.event.MouseEvent evt) {
        Main_Content.setVisible(true);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(false);

    }// GEN-LAST:event_home_iconMouseClicked

    private void aircraft_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_aircraft_iconMouseClicked
        // TODO add your handling code here:
        Main_Content.setVisible(false);
        aircraft_Panel.setVisible(true);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(false);
    }// GEN-LAST:event_aircraft_iconMouseClicked

    private void spacecraft_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_spacecraft_iconMouseClicked
        // TODO add your handling code here:
        Main_Content.setVisible(false);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(true);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(false);
    }// GEN-LAST:event_spacecraft_iconMouseClicked

    private void profile_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_profile_iconMouseClicked
        // TODO add your handling code here:
        Main_Content.setVisible(false);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(true);
        News_Panel.setVisible(false);
    }// GEN-LAST:event_profile_iconMouseClicked

    private void news_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_news_iconMouseClicked
        // TODO add your handling code here:
        Main_Content.setVisible(false);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(true);
    }// GEN-LAST:event_news_iconMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(
                    new java.net.URI(
                            "https://www.universetoday.com/articles/gravitational-lenses-deliver-a-verdict-on-the-hubble-tension"));
        } catch (IOException | URISyntaxException e) {
        }
    }// GEN-LAST:event_jLabel12MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(
                    new java.net.URI(
                            "https://www.bbc.com/future/article/20251201-how-cosmic-rays-grounded-thousands-of-aircraft"));
        } catch (IOException | URISyntaxException e) {
        }
    }// GEN-LAST:event_jLabel1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(
                    new java.net.URI("https://edition.cnn.com/2025/12/09/science/voyager-1-light-day-earth"));
        } catch (IOException | URISyntaxException e) {
        }
    }// GEN-LAST:event_jLabel11MouseClicked

    private void psfield_profileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_psfield_profileActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_psfield_profileActionPerformed

    private void designationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_designationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_designationActionPerformed

    private void PsField_loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PsField_loginActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PsField_loginActionPerformed

    private void Sign_upMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Sign_upMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "signup");
    }// GEN-LAST:event_Sign_upMouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jTextField5ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    String username = jTextField5.getText().trim();
    String password = jTextField1.getText().trim();
    String confirm  = jTextField2.getText().trim();
    String contact  = jTextField3.getText().trim();
    String address  = jTextField4.getText().trim();

    LoginController.SignupResult result =
            loginController.signup(username, password, confirm, contact, address);

    if (!result.success) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                result.message,
                "Signup Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(this, result.message);

    CardLayout card = (CardLayout) getContentPane().getLayout();
    card.show(getContentPane(), "login");
}


    private void AddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        AddCraftDetails frame = new AddCraftDetails(craftController);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loginPage.this.setEnabled(true); // Re-enable when closed
                loginPage.this.toFront(); // Bring dashboard back to front
            }
        });
        frame.setVisible(true);

    }

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RefreshMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_RefreshMouseClicked

    private void refreshCraftTable() {
        DefaultTableModel model = (DefaultTableModel) Dashboard_table.getModel(); // Use jTable1 (your table name)
        model.setRowCount(0);
        for (Craft c : craftController.getAllCrafts()) {
            model.addRow(new Object[] {
                    c.getName(),
                    c.getCraftType(),
                    // c.getEngineType(),
                    // c.getType(),
                    c.getPurpose(),
                    // c.getStatus()
            });
        }
    }
    private void refreshHistoryUI() {
        List<String> added = craftController.getRecentAdded();
        List<String> deleted = craftController.getRecentDeleted();
        recentlyaddedtext.setText(listToHtml(added));
        recentlydeletedfield.setText(listToHtml(deleted));
        undo.setEnabled(craftController.canUndoDelete());
    }

    private String listToHtml(List<String> items) {
        StringBuilder sb = new StringBuilder("<html>");
        int limit = Math.min(3, items.size());
        for (int i = 0; i < limit; i++) {
            sb.append("• ").append(items.get(i)).append("<br>");
        }
        sb.append("</html>");
        return sb.toString();
    }

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        // craftController.initializeSampleData(); // Already initialized in constructor
        refreshCraftTable();
        refreshHistoryUI();

    }// GEN-LAST:event_RefreshActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_reloadActionPerformed
        // jScrollPane1.removeAll();
        // craftController.initializeSampleData();
        for (int i = jPanel2.getComponentCount() - 1; i >= 0; i--) {
            if (jPanel2.getComponent(i) instanceof CraftPanel) {
                jPanel2.remove(i);
            }
        }

        // Add updated craft panels
        for (Craft craft : craftController.getAllCrafts()) {
            if (craft.getCraftType().equalsIgnoreCase("Aircraft")) {
                CraftPanel cp = new CraftPanel(craftController, craft, isAdmin);
                jPanel2.add(cp, 0); // add before filler
            }
        }

        jPanel2.revalidate();
        jPanel2.repaint();
        refreshHistoryUI();

    }// GEN-LAST:event_reloadActionPerformed

    private void Reoad_spaceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Reoad_spaceActionPerformed
        // TODO add your handling code here:
        // craftController.initializeSampleData();
        for (int i = jPanel4.getComponentCount() - 1; i >= 0; i--) {
            if (jPanel4.getComponent(i) instanceof CraftPanel) {
                jPanel4.remove(i);
            }
        }

        // Add updated craft panels
        for (Craft craft : craftController.getAllCrafts()) {
            if (craft.getCraftType().equalsIgnoreCase("Spacecraft")) {
                CraftPanel cp = new CraftPanel(craftController, craft, isAdmin);
                jPanel4.add(cp, 0); // add before filler
            }
        }

        jPanel4.revalidate();
        jPanel4.repaint();
        refreshHistoryUI();
    }// GEN-LAST:event_Reoad_spaceActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        name_txtfield.setEditable(true);
        psfield_profile.setEditable(true);
        contact_txtfield.setEditable(true);

        // UI hints (optional)
        name_txtfield.requestFocus();

        // enable save, disable edit
        savebtn1.setVisible(true);
        edit_btn.setVisible(false);

    }// GEN-LAST:event_edit_btnActionPerformed

    private void SortbynameMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_SortbynameMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_SortbynameMouseClicked

    private void SortbynameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SortbynameActionPerformed
        // TODO add your handling code here:
        if (nameSortAsc) {
            craftController.sortByName(true);
            // Sortbyname.setText("Sort by Name (Z → A)");
        } else {
            craftController.sortByName(false);
            // Sortbyname.setText("Sort by Name (A → Z)");
        }

        nameSortAsc = !nameSortAsc; // toggle state

        refreshCraftTable(); // refresh dashboard table
        reloadActionPerformed(null); // optional: refresh craft panels
    }// GEN-LAST:event_SortbynameActionPerformed

    private void DELETEDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DELETEDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_DELETEDActionPerformed

    private void recentlyaddedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_recentlyaddedActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_recentlyaddedActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_undoActionPerformed
        // TODO add your handling code here:
        Craft restored = craftController.undoLastDelete();

        if (restored == null) {
            JOptionPane.showMessageDialog(this, "Nothing to undo.");
            return;
        }

        // Refresh everything
        refreshCraftTable();
        reloadActionPerformed(null);
        Reoad_spaceActionPerformed(null);
        refreshHistoryUI();

        JOptionPane.showMessageDialog(this, restored.getName() + " restored!");
    }// GEN-LAST:event_undoActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here
    }// GEN-LAST:event_searchActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        if (search.getText().equals("Search by name")) {
            search.setText("");
            search.setForeground(java.awt.Color.BLACK);
        }
    }// GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_searchFocusLost
        // TODO add your handling code here:
        if (search.getText().trim().isEmpty()) {
            search.setText("Search by name");
            search.setForeground(java.awt.Color.GRAY);
        }
    }// GEN-LAST:event_searchFocusLost

   private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {
    String key = search.getText().trim();

    if (key.isEmpty() || key.equalsIgnoreCase("Search by name")) {
        JOptionPane.showMessageDialog(this, "Enter craft name to search");
        return;
    }
    DefaultTableModel model = (DefaultTableModel) Dashboard_table.getModel();
    model.setRowCount(0); // clear table first
    //Exact search (Binary)
    Craft exact = craftController.searchByName(key);

    if (exact != null) {
        model.addRow(new Object[]{
            exact.getName(),
            exact.getCraftType(),
            exact.getPurpose()
        });
        return; 
    }
    //Partial search (Linear)
    List<Craft> results = craftController.searchPartialByName(key);

    if (results.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No matching crafts found");
        return;
    }
    int LIMIT = 50;
    int count = 0;

    for (Craft c : results) {
        model.addRow(new Object[]{
            c.getName(),
            c.getCraftType(),
            c.getPurpose()
        });

        count++;
        if (count >= LIMIT) break;
    }
}



    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Do you want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION);

        if (choice != JOptionPane.YES_OPTION) {
            return; // user pressed No
        }
        // (Optional) clear login + profile fields
        Usernamefield_login.setText("");
        PsField_login.setText("");

        name_txtfield.setText("");
        psfield_profile.setText("");
        designation.setText("");
        contact_txtfield.setText("");

        // reset admin
        isAdmin = false;
        applyDashboardPrivileges();

        // go back to login page (CardLayout)
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "login");

        // (Optional) hide other panels inside dashboard
        Main_Content.setVisible(false);
        aircraft_Panel.setVisible(false);
        Spacecraft_Panel.setVisible(false);
        Profile_Panel.setVisible(false);
        News_Panel.setVisible(false);

    }// GEN-LAST:event_logout_buttonActionPerformed

    private void savebtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_savebtn1ActionPerformed
        // TODO add your handling code here:
    String name = name_txtfield.getText().trim();
    String pass = psfield_profile.getText().trim();
    String desig = designation.getText().trim();
    String contact = contact_txtfield.getText().trim();

    LoginController.ProfileResult res =
            loginController.updateProfile(name, pass, desig, contact);

    if (!res.success) {
        JOptionPane.showMessageDialog(this, res.message, "Profile Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(this, res.message);

    // lock fields again (UI only)
    name_txtfield.setEditable(false);
    psfield_profile.setEditable(false);
    designation.setEditable(false);
    contact_txtfield.setEditable(false);

    // toggle buttons (UI only)
    savebtn1.setVisible(false);
    edit_btn.setVisible(true);

    }// GEN-LAST:event_savebtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginPage().setVisible(true));

    }
    private void Usernamefield_loginActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO
    }

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Aeromaze;
    private javax.swing.JLabel Contact;
    private javax.swing.JTextField DELETED;
    private javax.swing.JPanel Dashboard_Panel;
    private javax.swing.JTable Dashboard_table;
    private javax.swing.JLabel Designation;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel Main_Content;
    private javax.swing.JPanel Nav_Panel;
    private javax.swing.JPanel News_Panel;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password_login;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JLabel Profile_Panel_Photo;
    private javax.swing.JLabel Profile_name;
    private javax.swing.JPasswordField PsField_login;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Reoad_space;
    private javax.swing.JLabel Sign_up;
    private javax.swing.JLabel Signup_label;
    private javax.swing.JButton Sortbyname;
    private javax.swing.JPanel Spacecraft_Panel;
    private javax.swing.JLabel Username_login;
    private javax.swing.JTextField Usernamefield_login;
    private javax.swing.JPanel aircraft_Panel;
    private javax.swing.JLabel aircraft_icon;
    private javax.swing.JTextField contact_txtfield;
    private javax.swing.JTextField designation;
    private javax.swing.JLabel earth;
    private javax.swing.JButton edit_btn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel home_icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel login_button;
    private javax.swing.JLabel login_icon;
    private javax.swing.JPanel login_panel;
    private javax.swing.JButton logout_button;
    private javax.swing.JLabel main_motto1;
    private javax.swing.JLabel main_motto2;
    private javax.swing.JLabel motto;
    private javax.swing.JTextField name_txtfield;
    private javax.swing.JLabel new_user;
    private javax.swing.JLabel news_icon;
    private javax.swing.JLabel news_photo;
    private javax.swing.JLabel profile_icon;
    private javax.swing.JTextField psfield_profile;
    private javax.swing.JTextField psfield_profile1;
    private javax.swing.JTextField recentlyadded;
    private javax.swing.JLabel recentlyaddedtext;
    private javax.swing.JLabel recentlydeletedfield;
    private javax.swing.JButton reload;
    private javax.swing.JButton savebtn1;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel searcher;
    private javax.swing.JPanel signUp_Panel;
    private javax.swing.JLabel signup_panel_photo;
    private javax.swing.JLabel spacecraft_icon;
    private javax.swing.JPanel top_Panel;
    private javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables
}